#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL_SIMS
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_SIMS")]
	public partial class DCSIMSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_account(TBL_account instance);
    partial void UpdateTBL_account(TBL_account instance);
    partial void DeleteTBL_account(TBL_account instance);
    partial void InsertTBL_menu(TBL_menu instance);
    partial void UpdateTBL_menu(TBL_menu instance);
    partial void DeleteTBL_menu(TBL_menu instance);
    partial void InsertTBL_role(TBL_role instance);
    partial void UpdateTBL_role(TBL_role instance);
    partial void DeleteTBL_role(TBL_role instance);
    partial void InsertTBL_rolemenu(TBL_rolemenu instance);
    partial void UpdateTBL_rolemenu(TBL_rolemenu instance);
    partial void DeleteTBL_rolemenu(TBL_rolemenu instance);
    partial void InsertTBL_university(TBL_university instance);
    partial void UpdateTBL_university(TBL_university instance);
    partial void DeleteTBL_university(TBL_university instance);
    partial void InsertTBL_usermenu(TBL_usermenu instance);
    partial void UpdateTBL_usermenu(TBL_usermenu instance);
    partial void DeleteTBL_usermenu(TBL_usermenu instance);
    partial void InsertTBL_userrole(TBL_userrole instance);
    partial void UpdateTBL_userrole(TBL_userrole instance);
    partial void DeleteTBL_userrole(TBL_userrole instance);
    #endregion
		
		public DCSIMSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCSIMSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCSIMSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCSIMSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_account> TBL_accounts
		{
			get
			{
				return this.GetTable<TBL_account>();
			}
		}
		
		public System.Data.Linq.Table<TBL_menu> TBL_menus
		{
			get
			{
				return this.GetTable<TBL_menu>();
			}
		}
		
		public System.Data.Linq.Table<TBL_role> TBL_roles
		{
			get
			{
				return this.GetTable<TBL_role>();
			}
		}
		
		public System.Data.Linq.Table<TBL_rolemenu> TBL_rolemenus
		{
			get
			{
				return this.GetTable<TBL_rolemenu>();
			}
		}
		
		public System.Data.Linq.Table<TBL_university> TBL_universities
		{
			get
			{
				return this.GetTable<TBL_university>();
			}
		}
		
		public System.Data.Linq.Table<TBL_usermenu> TBL_usermenus
		{
			get
			{
				return this.GetTable<TBL_usermenu>();
			}
		}
		
		public System.Data.Linq.Table<TBL_userrole> TBL_userroles
		{
			get
			{
				return this.GetTable<TBL_userrole>();
			}
		}
		
		public System.Data.Linq.Table<TBL_view_manegerole> TBL_view_manegeroles
		{
			get
			{
				return this.GetTable<TBL_view_manegerole>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_account")]
	public partial class TBL_account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _username;
		
		private string _password;
		
		private string _userstatus;
		
		private string _usertype;
		
		private System.Nullable<System.DateTime> _createdate;
		
		private System.Nullable<System.TimeSpan> _createtime;
		
		private System.Nullable<System.TimeSpan> _lastmodifieddate;
		
		private System.Nullable<System.TimeSpan> _lastmodifiedtime;
		
		private string _createdby;
		
		private string _lastmodifiedby;
		
		private string _loginstatus;
		
		private EntitySet<TBL_usermenu> _TBL_usermenus;
		
		private EntitySet<TBL_userrole> _TBL_userroles;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnuserstatusChanging(string value);
    partial void OnuserstatusChanged();
    partial void OnusertypeChanging(string value);
    partial void OnusertypeChanged();
    partial void OncreatedateChanging(System.Nullable<System.DateTime> value);
    partial void OncreatedateChanged();
    partial void OncreatetimeChanging(System.Nullable<System.TimeSpan> value);
    partial void OncreatetimeChanged();
    partial void OnlastmodifieddateChanging(System.Nullable<System.TimeSpan> value);
    partial void OnlastmodifieddateChanged();
    partial void OnlastmodifiedtimeChanging(System.Nullable<System.TimeSpan> value);
    partial void OnlastmodifiedtimeChanged();
    partial void OncreatedbyChanging(string value);
    partial void OncreatedbyChanged();
    partial void OnlastmodifiedbyChanging(string value);
    partial void OnlastmodifiedbyChanged();
    partial void OnloginstatusChanging(string value);
    partial void OnloginstatusChanged();
    #endregion
		
		public TBL_account()
		{
			this._TBL_usermenus = new EntitySet<TBL_usermenu>(new Action<TBL_usermenu>(this.attach_TBL_usermenus), new Action<TBL_usermenu>(this.detach_TBL_usermenus));
			this._TBL_userroles = new EntitySet<TBL_userrole>(new Action<TBL_userrole>(this.attach_TBL_userroles), new Action<TBL_userrole>(this.detach_TBL_userroles));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userstatus", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string userstatus
		{
			get
			{
				return this._userstatus;
			}
			set
			{
				if ((this._userstatus != value))
				{
					this.OnuserstatusChanging(value);
					this.SendPropertyChanging();
					this._userstatus = value;
					this.SendPropertyChanged("userstatus");
					this.OnuserstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usertype", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string usertype
		{
			get
			{
				return this._usertype;
			}
			set
			{
				if ((this._usertype != value))
				{
					this.OnusertypeChanging(value);
					this.SendPropertyChanging();
					this._usertype = value;
					this.SendPropertyChanged("usertype");
					this.OnusertypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdate", DbType="Date")]
		public System.Nullable<System.DateTime> createdate
		{
			get
			{
				return this._createdate;
			}
			set
			{
				if ((this._createdate != value))
				{
					this.OncreatedateChanging(value);
					this.SendPropertyChanging();
					this._createdate = value;
					this.SendPropertyChanged("createdate");
					this.OncreatedateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createtime", DbType="Time")]
		public System.Nullable<System.TimeSpan> createtime
		{
			get
			{
				return this._createtime;
			}
			set
			{
				if ((this._createtime != value))
				{
					this.OncreatetimeChanging(value);
					this.SendPropertyChanging();
					this._createtime = value;
					this.SendPropertyChanged("createtime");
					this.OncreatetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastmodifieddate", DbType="Time")]
		public System.Nullable<System.TimeSpan> lastmodifieddate
		{
			get
			{
				return this._lastmodifieddate;
			}
			set
			{
				if ((this._lastmodifieddate != value))
				{
					this.OnlastmodifieddateChanging(value);
					this.SendPropertyChanging();
					this._lastmodifieddate = value;
					this.SendPropertyChanged("lastmodifieddate");
					this.OnlastmodifieddateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastmodifiedtime", DbType="Time")]
		public System.Nullable<System.TimeSpan> lastmodifiedtime
		{
			get
			{
				return this._lastmodifiedtime;
			}
			set
			{
				if ((this._lastmodifiedtime != value))
				{
					this.OnlastmodifiedtimeChanging(value);
					this.SendPropertyChanging();
					this._lastmodifiedtime = value;
					this.SendPropertyChanged("lastmodifiedtime");
					this.OnlastmodifiedtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdby", DbType="VarChar(20)")]
		public string createdby
		{
			get
			{
				return this._createdby;
			}
			set
			{
				if ((this._createdby != value))
				{
					this.OncreatedbyChanging(value);
					this.SendPropertyChanging();
					this._createdby = value;
					this.SendPropertyChanged("createdby");
					this.OncreatedbyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastmodifiedby", DbType="VarChar(20)")]
		public string lastmodifiedby
		{
			get
			{
				return this._lastmodifiedby;
			}
			set
			{
				if ((this._lastmodifiedby != value))
				{
					this.OnlastmodifiedbyChanging(value);
					this.SendPropertyChanging();
					this._lastmodifiedby = value;
					this.SendPropertyChanged("lastmodifiedby");
					this.OnlastmodifiedbyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loginstatus", DbType="VarChar(2)")]
		public string loginstatus
		{
			get
			{
				return this._loginstatus;
			}
			set
			{
				if ((this._loginstatus != value))
				{
					this.OnloginstatusChanging(value);
					this.SendPropertyChanging();
					this._loginstatus = value;
					this.SendPropertyChanged("loginstatus");
					this.OnloginstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_account_TBL_usermenu", Storage="_TBL_usermenus", ThisKey="username", OtherKey="username")]
		public EntitySet<TBL_usermenu> TBL_usermenus
		{
			get
			{
				return this._TBL_usermenus;
			}
			set
			{
				this._TBL_usermenus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_account_TBL_userrole", Storage="_TBL_userroles", ThisKey="username", OtherKey="username")]
		public EntitySet<TBL_userrole> TBL_userroles
		{
			get
			{
				return this._TBL_userroles;
			}
			set
			{
				this._TBL_userroles.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_usermenus(TBL_usermenu entity)
		{
			this.SendPropertyChanging();
			entity.TBL_account = this;
		}
		
		private void detach_TBL_usermenus(TBL_usermenu entity)
		{
			this.SendPropertyChanging();
			entity.TBL_account = null;
		}
		
		private void attach_TBL_userroles(TBL_userrole entity)
		{
			this.SendPropertyChanging();
			entity.TBL_account = this;
		}
		
		private void detach_TBL_userroles(TBL_userrole entity)
		{
			this.SendPropertyChanging();
			entity.TBL_account = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_menu")]
	public partial class TBL_menu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _menuid;
		
		private int _parentid;
		
		private string _menuname;
		
		private string _menulink;
		
		private string _description;
		
		private System.Nullable<System.DateTime> _createdate;
		
		private System.Nullable<System.TimeSpan> _createtime;
		
		private System.Nullable<System.DateTime> _lastmodifieddate;
		
		private System.Nullable<System.TimeSpan> _lastmodifiedtime;
		
		private string _createdby;
		
		private string _lastmodifiedby;
		
		private string _status;
		
		private EntitySet<TBL_rolemenu> _TBL_rolemenus;
		
		private EntitySet<TBL_usermenu> _TBL_usermenus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmenuidChanging(int value);
    partial void OnmenuidChanged();
    partial void OnparentidChanging(int value);
    partial void OnparentidChanged();
    partial void OnmenunameChanging(string value);
    partial void OnmenunameChanged();
    partial void OnmenulinkChanging(string value);
    partial void OnmenulinkChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OncreatedateChanging(System.Nullable<System.DateTime> value);
    partial void OncreatedateChanged();
    partial void OncreatetimeChanging(System.Nullable<System.TimeSpan> value);
    partial void OncreatetimeChanged();
    partial void OnlastmodifieddateChanging(System.Nullable<System.DateTime> value);
    partial void OnlastmodifieddateChanged();
    partial void OnlastmodifiedtimeChanging(System.Nullable<System.TimeSpan> value);
    partial void OnlastmodifiedtimeChanged();
    partial void OncreatedbyChanging(string value);
    partial void OncreatedbyChanged();
    partial void OnlastmodifiedbyChanging(string value);
    partial void OnlastmodifiedbyChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    #endregion
		
		public TBL_menu()
		{
			this._TBL_rolemenus = new EntitySet<TBL_rolemenu>(new Action<TBL_rolemenu>(this.attach_TBL_rolemenus), new Action<TBL_rolemenu>(this.detach_TBL_rolemenus));
			this._TBL_usermenus = new EntitySet<TBL_usermenu>(new Action<TBL_usermenu>(this.attach_TBL_usermenus), new Action<TBL_usermenu>(this.detach_TBL_usermenus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menuid", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int menuid
		{
			get
			{
				return this._menuid;
			}
			set
			{
				if ((this._menuid != value))
				{
					this.OnmenuidChanging(value);
					this.SendPropertyChanging();
					this._menuid = value;
					this.SendPropertyChanged("menuid");
					this.OnmenuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parentid", DbType="Int NOT NULL")]
		public int parentid
		{
			get
			{
				return this._parentid;
			}
			set
			{
				if ((this._parentid != value))
				{
					this.OnparentidChanging(value);
					this.SendPropertyChanging();
					this._parentid = value;
					this.SendPropertyChanged("parentid");
					this.OnparentidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menuname", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string menuname
		{
			get
			{
				return this._menuname;
			}
			set
			{
				if ((this._menuname != value))
				{
					this.OnmenunameChanging(value);
					this.SendPropertyChanging();
					this._menuname = value;
					this.SendPropertyChanged("menuname");
					this.OnmenunameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menulink", DbType="VarChar(100)")]
		public string menulink
		{
			get
			{
				return this._menulink;
			}
			set
			{
				if ((this._menulink != value))
				{
					this.OnmenulinkChanging(value);
					this.SendPropertyChanging();
					this._menulink = value;
					this.SendPropertyChanged("menulink");
					this.OnmenulinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(100)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdate", DbType="Date")]
		public System.Nullable<System.DateTime> createdate
		{
			get
			{
				return this._createdate;
			}
			set
			{
				if ((this._createdate != value))
				{
					this.OncreatedateChanging(value);
					this.SendPropertyChanging();
					this._createdate = value;
					this.SendPropertyChanged("createdate");
					this.OncreatedateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createtime", DbType="Time")]
		public System.Nullable<System.TimeSpan> createtime
		{
			get
			{
				return this._createtime;
			}
			set
			{
				if ((this._createtime != value))
				{
					this.OncreatetimeChanging(value);
					this.SendPropertyChanging();
					this._createtime = value;
					this.SendPropertyChanged("createtime");
					this.OncreatetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastmodifieddate", DbType="Date")]
		public System.Nullable<System.DateTime> lastmodifieddate
		{
			get
			{
				return this._lastmodifieddate;
			}
			set
			{
				if ((this._lastmodifieddate != value))
				{
					this.OnlastmodifieddateChanging(value);
					this.SendPropertyChanging();
					this._lastmodifieddate = value;
					this.SendPropertyChanged("lastmodifieddate");
					this.OnlastmodifieddateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastmodifiedtime", DbType="Time")]
		public System.Nullable<System.TimeSpan> lastmodifiedtime
		{
			get
			{
				return this._lastmodifiedtime;
			}
			set
			{
				if ((this._lastmodifiedtime != value))
				{
					this.OnlastmodifiedtimeChanging(value);
					this.SendPropertyChanging();
					this._lastmodifiedtime = value;
					this.SendPropertyChanged("lastmodifiedtime");
					this.OnlastmodifiedtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdby", DbType="VarChar(20)")]
		public string createdby
		{
			get
			{
				return this._createdby;
			}
			set
			{
				if ((this._createdby != value))
				{
					this.OncreatedbyChanging(value);
					this.SendPropertyChanging();
					this._createdby = value;
					this.SendPropertyChanged("createdby");
					this.OncreatedbyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastmodifiedby", DbType="VarChar(20)")]
		public string lastmodifiedby
		{
			get
			{
				return this._lastmodifiedby;
			}
			set
			{
				if ((this._lastmodifiedby != value))
				{
					this.OnlastmodifiedbyChanging(value);
					this.SendPropertyChanging();
					this._lastmodifiedby = value;
					this.SendPropertyChanged("lastmodifiedby");
					this.OnlastmodifiedbyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(2)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_menu_TBL_rolemenu", Storage="_TBL_rolemenus", ThisKey="menuid", OtherKey="menuId")]
		public EntitySet<TBL_rolemenu> TBL_rolemenus
		{
			get
			{
				return this._TBL_rolemenus;
			}
			set
			{
				this._TBL_rolemenus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_menu_TBL_usermenu", Storage="_TBL_usermenus", ThisKey="menuid", OtherKey="menuId")]
		public EntitySet<TBL_usermenu> TBL_usermenus
		{
			get
			{
				return this._TBL_usermenus;
			}
			set
			{
				this._TBL_usermenus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_rolemenus(TBL_rolemenu entity)
		{
			this.SendPropertyChanging();
			entity.TBL_menu = this;
		}
		
		private void detach_TBL_rolemenus(TBL_rolemenu entity)
		{
			this.SendPropertyChanging();
			entity.TBL_menu = null;
		}
		
		private void attach_TBL_usermenus(TBL_usermenu entity)
		{
			this.SendPropertyChanging();
			entity.TBL_menu = this;
		}
		
		private void detach_TBL_usermenus(TBL_usermenu entity)
		{
			this.SendPropertyChanging();
			entity.TBL_menu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_role")]
	public partial class TBL_role : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _roleid;
		
		private string _rolename;
		
		private System.Nullable<System.DateTime> _createdate;
		
		private System.Nullable<System.TimeSpan> _createtime;
		
		private System.Nullable<System.TimeSpan> _lastmodifieddate;
		
		private System.Nullable<System.TimeSpan> _lastmodifiedtime;
		
		private string _createdby;
		
		private string _lastmodifiedby;
		
		private string _status;
		
		private EntitySet<TBL_rolemenu> _TBL_rolemenus;
		
		private EntitySet<TBL_userrole> _TBL_userroles;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnroleidChanging(string value);
    partial void OnroleidChanged();
    partial void OnrolenameChanging(string value);
    partial void OnrolenameChanged();
    partial void OncreatedateChanging(System.Nullable<System.DateTime> value);
    partial void OncreatedateChanged();
    partial void OncreatetimeChanging(System.Nullable<System.TimeSpan> value);
    partial void OncreatetimeChanged();
    partial void OnlastmodifieddateChanging(System.Nullable<System.TimeSpan> value);
    partial void OnlastmodifieddateChanged();
    partial void OnlastmodifiedtimeChanging(System.Nullable<System.TimeSpan> value);
    partial void OnlastmodifiedtimeChanged();
    partial void OncreatedbyChanging(string value);
    partial void OncreatedbyChanged();
    partial void OnlastmodifiedbyChanging(string value);
    partial void OnlastmodifiedbyChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    #endregion
		
		public TBL_role()
		{
			this._TBL_rolemenus = new EntitySet<TBL_rolemenu>(new Action<TBL_rolemenu>(this.attach_TBL_rolemenus), new Action<TBL_rolemenu>(this.detach_TBL_rolemenus));
			this._TBL_userroles = new EntitySet<TBL_userrole>(new Action<TBL_userrole>(this.attach_TBL_userroles), new Action<TBL_userrole>(this.detach_TBL_userroles));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_roleid", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string roleid
		{
			get
			{
				return this._roleid;
			}
			set
			{
				if ((this._roleid != value))
				{
					this.OnroleidChanging(value);
					this.SendPropertyChanging();
					this._roleid = value;
					this.SendPropertyChanged("roleid");
					this.OnroleidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rolename", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string rolename
		{
			get
			{
				return this._rolename;
			}
			set
			{
				if ((this._rolename != value))
				{
					this.OnrolenameChanging(value);
					this.SendPropertyChanging();
					this._rolename = value;
					this.SendPropertyChanged("rolename");
					this.OnrolenameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdate", DbType="Date")]
		public System.Nullable<System.DateTime> createdate
		{
			get
			{
				return this._createdate;
			}
			set
			{
				if ((this._createdate != value))
				{
					this.OncreatedateChanging(value);
					this.SendPropertyChanging();
					this._createdate = value;
					this.SendPropertyChanged("createdate");
					this.OncreatedateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createtime", DbType="Time")]
		public System.Nullable<System.TimeSpan> createtime
		{
			get
			{
				return this._createtime;
			}
			set
			{
				if ((this._createtime != value))
				{
					this.OncreatetimeChanging(value);
					this.SendPropertyChanging();
					this._createtime = value;
					this.SendPropertyChanged("createtime");
					this.OncreatetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastmodifieddate", DbType="Time")]
		public System.Nullable<System.TimeSpan> lastmodifieddate
		{
			get
			{
				return this._lastmodifieddate;
			}
			set
			{
				if ((this._lastmodifieddate != value))
				{
					this.OnlastmodifieddateChanging(value);
					this.SendPropertyChanging();
					this._lastmodifieddate = value;
					this.SendPropertyChanged("lastmodifieddate");
					this.OnlastmodifieddateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastmodifiedtime", DbType="Time")]
		public System.Nullable<System.TimeSpan> lastmodifiedtime
		{
			get
			{
				return this._lastmodifiedtime;
			}
			set
			{
				if ((this._lastmodifiedtime != value))
				{
					this.OnlastmodifiedtimeChanging(value);
					this.SendPropertyChanging();
					this._lastmodifiedtime = value;
					this.SendPropertyChanged("lastmodifiedtime");
					this.OnlastmodifiedtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdby", DbType="VarChar(20)")]
		public string createdby
		{
			get
			{
				return this._createdby;
			}
			set
			{
				if ((this._createdby != value))
				{
					this.OncreatedbyChanging(value);
					this.SendPropertyChanging();
					this._createdby = value;
					this.SendPropertyChanged("createdby");
					this.OncreatedbyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastmodifiedby", DbType="VarChar(20)")]
		public string lastmodifiedby
		{
			get
			{
				return this._lastmodifiedby;
			}
			set
			{
				if ((this._lastmodifiedby != value))
				{
					this.OnlastmodifiedbyChanging(value);
					this.SendPropertyChanging();
					this._lastmodifiedby = value;
					this.SendPropertyChanged("lastmodifiedby");
					this.OnlastmodifiedbyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(2)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_role_TBL_rolemenu", Storage="_TBL_rolemenus", ThisKey="roleid", OtherKey="roleid")]
		public EntitySet<TBL_rolemenu> TBL_rolemenus
		{
			get
			{
				return this._TBL_rolemenus;
			}
			set
			{
				this._TBL_rolemenus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_role_TBL_userrole", Storage="_TBL_userroles", ThisKey="roleid", OtherKey="roleid")]
		public EntitySet<TBL_userrole> TBL_userroles
		{
			get
			{
				return this._TBL_userroles;
			}
			set
			{
				this._TBL_userroles.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_rolemenus(TBL_rolemenu entity)
		{
			this.SendPropertyChanging();
			entity.TBL_role = this;
		}
		
		private void detach_TBL_rolemenus(TBL_rolemenu entity)
		{
			this.SendPropertyChanging();
			entity.TBL_role = null;
		}
		
		private void attach_TBL_userroles(TBL_userrole entity)
		{
			this.SendPropertyChanging();
			entity.TBL_role = this;
		}
		
		private void detach_TBL_userroles(TBL_userrole entity)
		{
			this.SendPropertyChanging();
			entity.TBL_role = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_rolemenu")]
	public partial class TBL_rolemenu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _roleid;
		
		private System.Nullable<int> _menuId;
		
		private string _status;
		
		private System.Nullable<System.DateTime> _assigneddate;
		
		private System.Nullable<System.DateTime> _lastassignedddate;
		
		private System.Nullable<System.TimeSpan> _assignedtime;
		
		private System.Nullable<System.TimeSpan> _lastassignedtime;
		
		private string _assignedby;
		
		private string _lastassignedby;
		
		private EntityRef<TBL_menu> _TBL_menu;
		
		private EntityRef<TBL_role> _TBL_role;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnroleidChanging(string value);
    partial void OnroleidChanged();
    partial void OnmenuIdChanging(System.Nullable<int> value);
    partial void OnmenuIdChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void OnassigneddateChanging(System.Nullable<System.DateTime> value);
    partial void OnassigneddateChanged();
    partial void OnlastassignedddateChanging(System.Nullable<System.DateTime> value);
    partial void OnlastassignedddateChanged();
    partial void OnassignedtimeChanging(System.Nullable<System.TimeSpan> value);
    partial void OnassignedtimeChanged();
    partial void OnlastassignedtimeChanging(System.Nullable<System.TimeSpan> value);
    partial void OnlastassignedtimeChanged();
    partial void OnassignedbyChanging(string value);
    partial void OnassignedbyChanged();
    partial void OnlastassignedbyChanging(string value);
    partial void OnlastassignedbyChanged();
    #endregion
		
		public TBL_rolemenu()
		{
			this._TBL_menu = default(EntityRef<TBL_menu>);
			this._TBL_role = default(EntityRef<TBL_role>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_roleid", DbType="VarChar(20)")]
		public string roleid
		{
			get
			{
				return this._roleid;
			}
			set
			{
				if ((this._roleid != value))
				{
					if (this._TBL_role.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnroleidChanging(value);
					this.SendPropertyChanging();
					this._roleid = value;
					this.SendPropertyChanged("roleid");
					this.OnroleidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menuId", DbType="Int")]
		public System.Nullable<int> menuId
		{
			get
			{
				return this._menuId;
			}
			set
			{
				if ((this._menuId != value))
				{
					if (this._TBL_menu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmenuIdChanging(value);
					this.SendPropertyChanging();
					this._menuId = value;
					this.SendPropertyChanged("menuId");
					this.OnmenuIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(2)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_assigneddate", DbType="Date")]
		public System.Nullable<System.DateTime> assigneddate
		{
			get
			{
				return this._assigneddate;
			}
			set
			{
				if ((this._assigneddate != value))
				{
					this.OnassigneddateChanging(value);
					this.SendPropertyChanging();
					this._assigneddate = value;
					this.SendPropertyChanged("assigneddate");
					this.OnassigneddateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastassignedddate", DbType="Date")]
		public System.Nullable<System.DateTime> lastassignedddate
		{
			get
			{
				return this._lastassignedddate;
			}
			set
			{
				if ((this._lastassignedddate != value))
				{
					this.OnlastassignedddateChanging(value);
					this.SendPropertyChanging();
					this._lastassignedddate = value;
					this.SendPropertyChanged("lastassignedddate");
					this.OnlastassignedddateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_assignedtime", DbType="Time")]
		public System.Nullable<System.TimeSpan> assignedtime
		{
			get
			{
				return this._assignedtime;
			}
			set
			{
				if ((this._assignedtime != value))
				{
					this.OnassignedtimeChanging(value);
					this.SendPropertyChanging();
					this._assignedtime = value;
					this.SendPropertyChanged("assignedtime");
					this.OnassignedtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastassignedtime", DbType="Time")]
		public System.Nullable<System.TimeSpan> lastassignedtime
		{
			get
			{
				return this._lastassignedtime;
			}
			set
			{
				if ((this._lastassignedtime != value))
				{
					this.OnlastassignedtimeChanging(value);
					this.SendPropertyChanging();
					this._lastassignedtime = value;
					this.SendPropertyChanged("lastassignedtime");
					this.OnlastassignedtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_assignedby", DbType="VarChar(20)")]
		public string assignedby
		{
			get
			{
				return this._assignedby;
			}
			set
			{
				if ((this._assignedby != value))
				{
					this.OnassignedbyChanging(value);
					this.SendPropertyChanging();
					this._assignedby = value;
					this.SendPropertyChanged("assignedby");
					this.OnassignedbyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastassignedby", DbType="VarChar(20)")]
		public string lastassignedby
		{
			get
			{
				return this._lastassignedby;
			}
			set
			{
				if ((this._lastassignedby != value))
				{
					this.OnlastassignedbyChanging(value);
					this.SendPropertyChanging();
					this._lastassignedby = value;
					this.SendPropertyChanged("lastassignedby");
					this.OnlastassignedbyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_menu_TBL_rolemenu", Storage="_TBL_menu", ThisKey="menuId", OtherKey="menuid", IsForeignKey=true)]
		public TBL_menu TBL_menu
		{
			get
			{
				return this._TBL_menu.Entity;
			}
			set
			{
				TBL_menu previousValue = this._TBL_menu.Entity;
				if (((previousValue != value) 
							|| (this._TBL_menu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_menu.Entity = null;
						previousValue.TBL_rolemenus.Remove(this);
					}
					this._TBL_menu.Entity = value;
					if ((value != null))
					{
						value.TBL_rolemenus.Add(this);
						this._menuId = value.menuid;
					}
					else
					{
						this._menuId = default(Nullable<int>);
					}
					this.SendPropertyChanged("TBL_menu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_role_TBL_rolemenu", Storage="_TBL_role", ThisKey="roleid", OtherKey="roleid", IsForeignKey=true)]
		public TBL_role TBL_role
		{
			get
			{
				return this._TBL_role.Entity;
			}
			set
			{
				TBL_role previousValue = this._TBL_role.Entity;
				if (((previousValue != value) 
							|| (this._TBL_role.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_role.Entity = null;
						previousValue.TBL_rolemenus.Remove(this);
					}
					this._TBL_role.Entity = value;
					if ((value != null))
					{
						value.TBL_rolemenus.Add(this);
						this._roleid = value.roleid;
					}
					else
					{
						this._roleid = default(string);
					}
					this.SendPropertyChanged("TBL_role");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_university")]
	public partial class TBL_university : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _univid;
		
		private string _univname;
		
		private System.Nullable<System.DateTime> _createddate;
		
		private System.Nullable<System.TimeSpan> _createdtime;
		
		private string _createdby;
		
		private System.Nullable<System.DateTime> _modifieddate;
		
		private System.Nullable<System.TimeSpan> _modifiedtime;
		
		private string _modifiedby;
		
		private string _status;
		
		private string _systid;
		
		private string _systname;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnunividChanging(string value);
    partial void OnunividChanged();
    partial void OnunivnameChanging(string value);
    partial void OnunivnameChanged();
    partial void OncreateddateChanging(System.Nullable<System.DateTime> value);
    partial void OncreateddateChanged();
    partial void OncreatedtimeChanging(System.Nullable<System.TimeSpan> value);
    partial void OncreatedtimeChanged();
    partial void OncreatedbyChanging(string value);
    partial void OncreatedbyChanged();
    partial void OnmodifieddateChanging(System.Nullable<System.DateTime> value);
    partial void OnmodifieddateChanged();
    partial void OnmodifiedtimeChanging(System.Nullable<System.TimeSpan> value);
    partial void OnmodifiedtimeChanged();
    partial void OnmodifiedbyChanging(string value);
    partial void OnmodifiedbyChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void OnsystidChanging(string value);
    partial void OnsystidChanged();
    partial void OnsystnameChanging(string value);
    partial void OnsystnameChanged();
    #endregion
		
		public TBL_university()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_univid", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string univid
		{
			get
			{
				return this._univid;
			}
			set
			{
				if ((this._univid != value))
				{
					this.OnunividChanging(value);
					this.SendPropertyChanging();
					this._univid = value;
					this.SendPropertyChanged("univid");
					this.OnunividChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_univname", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string univname
		{
			get
			{
				return this._univname;
			}
			set
			{
				if ((this._univname != value))
				{
					this.OnunivnameChanging(value);
					this.SendPropertyChanging();
					this._univname = value;
					this.SendPropertyChanged("univname");
					this.OnunivnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createddate", DbType="Date")]
		public System.Nullable<System.DateTime> createddate
		{
			get
			{
				return this._createddate;
			}
			set
			{
				if ((this._createddate != value))
				{
					this.OncreateddateChanging(value);
					this.SendPropertyChanging();
					this._createddate = value;
					this.SendPropertyChanged("createddate");
					this.OncreateddateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdtime", DbType="Time")]
		public System.Nullable<System.TimeSpan> createdtime
		{
			get
			{
				return this._createdtime;
			}
			set
			{
				if ((this._createdtime != value))
				{
					this.OncreatedtimeChanging(value);
					this.SendPropertyChanging();
					this._createdtime = value;
					this.SendPropertyChanged("createdtime");
					this.OncreatedtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdby", DbType="VarChar(20)")]
		public string createdby
		{
			get
			{
				return this._createdby;
			}
			set
			{
				if ((this._createdby != value))
				{
					this.OncreatedbyChanging(value);
					this.SendPropertyChanging();
					this._createdby = value;
					this.SendPropertyChanged("createdby");
					this.OncreatedbyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modifieddate", DbType="Date")]
		public System.Nullable<System.DateTime> modifieddate
		{
			get
			{
				return this._modifieddate;
			}
			set
			{
				if ((this._modifieddate != value))
				{
					this.OnmodifieddateChanging(value);
					this.SendPropertyChanging();
					this._modifieddate = value;
					this.SendPropertyChanged("modifieddate");
					this.OnmodifieddateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modifiedtime", DbType="Time")]
		public System.Nullable<System.TimeSpan> modifiedtime
		{
			get
			{
				return this._modifiedtime;
			}
			set
			{
				if ((this._modifiedtime != value))
				{
					this.OnmodifiedtimeChanging(value);
					this.SendPropertyChanging();
					this._modifiedtime = value;
					this.SendPropertyChanged("modifiedtime");
					this.OnmodifiedtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modifiedby", DbType="VarChar(20)")]
		public string modifiedby
		{
			get
			{
				return this._modifiedby;
			}
			set
			{
				if ((this._modifiedby != value))
				{
					this.OnmodifiedbyChanging(value);
					this.SendPropertyChanging();
					this._modifiedby = value;
					this.SendPropertyChanged("modifiedby");
					this.OnmodifiedbyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(2)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_systid", DbType="VarChar(20)")]
		public string systid
		{
			get
			{
				return this._systid;
			}
			set
			{
				if ((this._systid != value))
				{
					this.OnsystidChanging(value);
					this.SendPropertyChanging();
					this._systid = value;
					this.SendPropertyChanged("systid");
					this.OnsystidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_systname", DbType="VarChar(100)")]
		public string systname
		{
			get
			{
				return this._systname;
			}
			set
			{
				if ((this._systname != value))
				{
					this.OnsystnameChanging(value);
					this.SendPropertyChanging();
					this._systname = value;
					this.SendPropertyChanged("systname");
					this.OnsystnameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_usermenu")]
	public partial class TBL_usermenu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _username;
		
		private System.Nullable<int> _menuId;
		
		private string _status;
		
		private System.Nullable<System.DateTime> _assigneddate;
		
		private System.Nullable<System.DateTime> _lastassignedddate;
		
		private System.Nullable<System.TimeSpan> _assignedtime;
		
		private System.Nullable<System.TimeSpan> _lastassignedtime;
		
		private string _assignedby;
		
		private string _lastassignedby;
		
		private EntityRef<TBL_menu> _TBL_menu;
		
		private EntityRef<TBL_account> _TBL_account;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnmenuIdChanging(System.Nullable<int> value);
    partial void OnmenuIdChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void OnassigneddateChanging(System.Nullable<System.DateTime> value);
    partial void OnassigneddateChanged();
    partial void OnlastassignedddateChanging(System.Nullable<System.DateTime> value);
    partial void OnlastassignedddateChanged();
    partial void OnassignedtimeChanging(System.Nullable<System.TimeSpan> value);
    partial void OnassignedtimeChanged();
    partial void OnlastassignedtimeChanging(System.Nullable<System.TimeSpan> value);
    partial void OnlastassignedtimeChanged();
    partial void OnassignedbyChanging(string value);
    partial void OnassignedbyChanged();
    partial void OnlastassignedbyChanging(string value);
    partial void OnlastassignedbyChanged();
    #endregion
		
		public TBL_usermenu()
		{
			this._TBL_menu = default(EntityRef<TBL_menu>);
			this._TBL_account = default(EntityRef<TBL_account>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(20)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					if (this._TBL_account.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menuId", DbType="Int")]
		public System.Nullable<int> menuId
		{
			get
			{
				return this._menuId;
			}
			set
			{
				if ((this._menuId != value))
				{
					if (this._TBL_menu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmenuIdChanging(value);
					this.SendPropertyChanging();
					this._menuId = value;
					this.SendPropertyChanged("menuId");
					this.OnmenuIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(2)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_assigneddate", DbType="Date")]
		public System.Nullable<System.DateTime> assigneddate
		{
			get
			{
				return this._assigneddate;
			}
			set
			{
				if ((this._assigneddate != value))
				{
					this.OnassigneddateChanging(value);
					this.SendPropertyChanging();
					this._assigneddate = value;
					this.SendPropertyChanged("assigneddate");
					this.OnassigneddateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastassignedddate", DbType="Date")]
		public System.Nullable<System.DateTime> lastassignedddate
		{
			get
			{
				return this._lastassignedddate;
			}
			set
			{
				if ((this._lastassignedddate != value))
				{
					this.OnlastassignedddateChanging(value);
					this.SendPropertyChanging();
					this._lastassignedddate = value;
					this.SendPropertyChanged("lastassignedddate");
					this.OnlastassignedddateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_assignedtime", DbType="Time")]
		public System.Nullable<System.TimeSpan> assignedtime
		{
			get
			{
				return this._assignedtime;
			}
			set
			{
				if ((this._assignedtime != value))
				{
					this.OnassignedtimeChanging(value);
					this.SendPropertyChanging();
					this._assignedtime = value;
					this.SendPropertyChanged("assignedtime");
					this.OnassignedtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastassignedtime", DbType="Time")]
		public System.Nullable<System.TimeSpan> lastassignedtime
		{
			get
			{
				return this._lastassignedtime;
			}
			set
			{
				if ((this._lastassignedtime != value))
				{
					this.OnlastassignedtimeChanging(value);
					this.SendPropertyChanging();
					this._lastassignedtime = value;
					this.SendPropertyChanged("lastassignedtime");
					this.OnlastassignedtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_assignedby", DbType="VarChar(20)")]
		public string assignedby
		{
			get
			{
				return this._assignedby;
			}
			set
			{
				if ((this._assignedby != value))
				{
					this.OnassignedbyChanging(value);
					this.SendPropertyChanging();
					this._assignedby = value;
					this.SendPropertyChanged("assignedby");
					this.OnassignedbyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastassignedby", DbType="VarChar(20)")]
		public string lastassignedby
		{
			get
			{
				return this._lastassignedby;
			}
			set
			{
				if ((this._lastassignedby != value))
				{
					this.OnlastassignedbyChanging(value);
					this.SendPropertyChanging();
					this._lastassignedby = value;
					this.SendPropertyChanged("lastassignedby");
					this.OnlastassignedbyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_menu_TBL_usermenu", Storage="_TBL_menu", ThisKey="menuId", OtherKey="menuid", IsForeignKey=true)]
		public TBL_menu TBL_menu
		{
			get
			{
				return this._TBL_menu.Entity;
			}
			set
			{
				TBL_menu previousValue = this._TBL_menu.Entity;
				if (((previousValue != value) 
							|| (this._TBL_menu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_menu.Entity = null;
						previousValue.TBL_usermenus.Remove(this);
					}
					this._TBL_menu.Entity = value;
					if ((value != null))
					{
						value.TBL_usermenus.Add(this);
						this._menuId = value.menuid;
					}
					else
					{
						this._menuId = default(Nullable<int>);
					}
					this.SendPropertyChanged("TBL_menu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_account_TBL_usermenu", Storage="_TBL_account", ThisKey="username", OtherKey="username", IsForeignKey=true)]
		public TBL_account TBL_account
		{
			get
			{
				return this._TBL_account.Entity;
			}
			set
			{
				TBL_account previousValue = this._TBL_account.Entity;
				if (((previousValue != value) 
							|| (this._TBL_account.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_account.Entity = null;
						previousValue.TBL_usermenus.Remove(this);
					}
					this._TBL_account.Entity = value;
					if ((value != null))
					{
						value.TBL_usermenus.Add(this);
						this._username = value.username;
					}
					else
					{
						this._username = default(string);
					}
					this.SendPropertyChanged("TBL_account");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_userrole")]
	public partial class TBL_userrole : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _userroleid;
		
		private string _username;
		
		private string _roleid;
		
		private System.Nullable<System.DateTime> _assigneddate;
		
		private System.Nullable<System.TimeSpan> _assignedtime;
		
		private System.Nullable<System.DateTime> _lastassignedddate;
		
		private System.Nullable<System.TimeSpan> _lastassignedtime;
		
		private string _assignedby;
		
		private string _lastassignedby;
		
		private string _status;
		
		private EntityRef<TBL_role> _TBL_role;
		
		private EntityRef<TBL_account> _TBL_account;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnuserroleidChanging(string value);
    partial void OnuserroleidChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnroleidChanging(string value);
    partial void OnroleidChanged();
    partial void OnassigneddateChanging(System.Nullable<System.DateTime> value);
    partial void OnassigneddateChanged();
    partial void OnassignedtimeChanging(System.Nullable<System.TimeSpan> value);
    partial void OnassignedtimeChanged();
    partial void OnlastassignedddateChanging(System.Nullable<System.DateTime> value);
    partial void OnlastassignedddateChanged();
    partial void OnlastassignedtimeChanging(System.Nullable<System.TimeSpan> value);
    partial void OnlastassignedtimeChanged();
    partial void OnassignedbyChanging(string value);
    partial void OnassignedbyChanged();
    partial void OnlastassignedbyChanging(string value);
    partial void OnlastassignedbyChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    #endregion
		
		public TBL_userrole()
		{
			this._TBL_role = default(EntityRef<TBL_role>);
			this._TBL_account = default(EntityRef<TBL_account>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userroleid", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string userroleid
		{
			get
			{
				return this._userroleid;
			}
			set
			{
				if ((this._userroleid != value))
				{
					this.OnuserroleidChanging(value);
					this.SendPropertyChanging();
					this._userroleid = value;
					this.SendPropertyChanged("userroleid");
					this.OnuserroleidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(20)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					if (this._TBL_account.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_roleid", DbType="VarChar(20)")]
		public string roleid
		{
			get
			{
				return this._roleid;
			}
			set
			{
				if ((this._roleid != value))
				{
					if (this._TBL_role.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnroleidChanging(value);
					this.SendPropertyChanging();
					this._roleid = value;
					this.SendPropertyChanged("roleid");
					this.OnroleidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_assigneddate", DbType="Date")]
		public System.Nullable<System.DateTime> assigneddate
		{
			get
			{
				return this._assigneddate;
			}
			set
			{
				if ((this._assigneddate != value))
				{
					this.OnassigneddateChanging(value);
					this.SendPropertyChanging();
					this._assigneddate = value;
					this.SendPropertyChanged("assigneddate");
					this.OnassigneddateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_assignedtime", DbType="Time")]
		public System.Nullable<System.TimeSpan> assignedtime
		{
			get
			{
				return this._assignedtime;
			}
			set
			{
				if ((this._assignedtime != value))
				{
					this.OnassignedtimeChanging(value);
					this.SendPropertyChanging();
					this._assignedtime = value;
					this.SendPropertyChanged("assignedtime");
					this.OnassignedtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastassignedddate", DbType="Date")]
		public System.Nullable<System.DateTime> lastassignedddate
		{
			get
			{
				return this._lastassignedddate;
			}
			set
			{
				if ((this._lastassignedddate != value))
				{
					this.OnlastassignedddateChanging(value);
					this.SendPropertyChanging();
					this._lastassignedddate = value;
					this.SendPropertyChanged("lastassignedddate");
					this.OnlastassignedddateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastassignedtime", DbType="Time")]
		public System.Nullable<System.TimeSpan> lastassignedtime
		{
			get
			{
				return this._lastassignedtime;
			}
			set
			{
				if ((this._lastassignedtime != value))
				{
					this.OnlastassignedtimeChanging(value);
					this.SendPropertyChanging();
					this._lastassignedtime = value;
					this.SendPropertyChanged("lastassignedtime");
					this.OnlastassignedtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_assignedby", DbType="VarChar(20)")]
		public string assignedby
		{
			get
			{
				return this._assignedby;
			}
			set
			{
				if ((this._assignedby != value))
				{
					this.OnassignedbyChanging(value);
					this.SendPropertyChanging();
					this._assignedby = value;
					this.SendPropertyChanged("assignedby");
					this.OnassignedbyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastassignedby", DbType="VarChar(20)")]
		public string lastassignedby
		{
			get
			{
				return this._lastassignedby;
			}
			set
			{
				if ((this._lastassignedby != value))
				{
					this.OnlastassignedbyChanging(value);
					this.SendPropertyChanging();
					this._lastassignedby = value;
					this.SendPropertyChanged("lastassignedby");
					this.OnlastassignedbyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(2)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_role_TBL_userrole", Storage="_TBL_role", ThisKey="roleid", OtherKey="roleid", IsForeignKey=true)]
		public TBL_role TBL_role
		{
			get
			{
				return this._TBL_role.Entity;
			}
			set
			{
				TBL_role previousValue = this._TBL_role.Entity;
				if (((previousValue != value) 
							|| (this._TBL_role.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_role.Entity = null;
						previousValue.TBL_userroles.Remove(this);
					}
					this._TBL_role.Entity = value;
					if ((value != null))
					{
						value.TBL_userroles.Add(this);
						this._roleid = value.roleid;
					}
					else
					{
						this._roleid = default(string);
					}
					this.SendPropertyChanged("TBL_role");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_account_TBL_userrole", Storage="_TBL_account", ThisKey="username", OtherKey="username", IsForeignKey=true)]
		public TBL_account TBL_account
		{
			get
			{
				return this._TBL_account.Entity;
			}
			set
			{
				TBL_account previousValue = this._TBL_account.Entity;
				if (((previousValue != value) 
							|| (this._TBL_account.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_account.Entity = null;
						previousValue.TBL_userroles.Remove(this);
					}
					this._TBL_account.Entity = value;
					if ((value != null))
					{
						value.TBL_userroles.Add(this);
						this._username = value.username;
					}
					else
					{
						this._username = default(string);
					}
					this.SendPropertyChanged("TBL_account");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_view_manegerole")]
	public partial class TBL_view_manegerole
	{
		
		private string _username;
		
		private int _menuid;
		
		private int _parentid;
		
		private string _menuname;
		
		private string _menulink;
		
		public TBL_view_manegerole()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(20)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this._username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menuid", DbType="Int NOT NULL")]
		public int menuid
		{
			get
			{
				return this._menuid;
			}
			set
			{
				if ((this._menuid != value))
				{
					this._menuid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parentid", DbType="Int NOT NULL")]
		public int parentid
		{
			get
			{
				return this._parentid;
			}
			set
			{
				if ((this._parentid != value))
				{
					this._parentid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menuname", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string menuname
		{
			get
			{
				return this._menuname;
			}
			set
			{
				if ((this._menuname != value))
				{
					this._menuname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menulink", DbType="VarChar(100)")]
		public string menulink
		{
			get
			{
				return this._menulink;
			}
			set
			{
				if ((this._menulink != value))
				{
					this._menulink = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
